// packages/channel-client/src/react-template.ts
/**
 * React runtime template.
 *
 * This module exports a single function `renderReactRuntime()` that
 * returns the full TypeScript source for the `react-runtime.ts` file
 * emitted alongside the generated React hook files.
 *
 * The runtime is transport-agnostic with respect to the concrete
 * channel type: it provides `useTriadChannelLifecycle<TClient>()`, a
 * generic hook that owns the client reference across renders and
 * subscribes to its state via `useSyncExternalStore`. Per-channel
 * hooks (emitted by `react-hook-generator.ts`) wrap this with typed
 * callbacks.
 *
 * Why a string and not a real source file we copy? Keeping it inline
 * lets the generator ship as a single published package without any
 * runtime React dependency — `@triadjs/channel-client` itself has no
 * React in its dependency tree, the generated code does.
 */

export function renderReactRuntime(): string {
  return `// Generated by @triadjs/channel-client — do not edit.
// Regenerate with: triad frontend generate --target channel-client-react

import { useSyncExternalStore, useEffect, useRef } from 'react';
import type { ChannelState } from './client.js';

/**
 * Minimal structural shape every generated channel client satisfies.
 * The React lifecycle hook works against this interface so it does
 * not need a per-channel import.
 */
export interface TriadChannelClientLike {
  readonly state: ChannelState;
  on(event: 'stateChange', cb: (state: ChannelState) => void): () => void;
  close(): Promise<void>;
}

export interface UseTriadChannelResult<TClient extends TriadChannelClientLike> {
  /** Stable client reference across renders. */
  client: TClient;
  /** Current connection state; re-renders on transition. */
  state: ChannelState;
  /** Convenience flag equivalent to \`state === 'open'\`. */
  isOpen: boolean;
}

export interface UseTriadChannelLifecycleOptions {
  /**
   * When \`false\`, the hook does not create a client and returns a
   * dummy disconnected result. Flipping back to \`true\` creates a
   * fresh client. Defaults to \`true\`.
   */
  enabled?: boolean;
}

/**
 * Own a channel client across the lifetime of a React component.
 *
 * - The factory is invoked exactly once per mount (while \`enabled\`).
 * - On unmount, or when \`enabled\` flips false, \`client.close()\` is called.
 * - Re-renders are driven by the client's \`stateChange\` event via
 *   \`useSyncExternalStore\`, so a \`connecting → open\` transition
 *   will re-render the component.
 *
 * Changing connection options (url, params, headers) at runtime is
 * NOT supported: the factory runs once. To reconnect against different
 * options, change the component's \`key\` prop so React remounts it.
 */
export function useTriadChannelLifecycle<TClient extends TriadChannelClientLike>(
  factory: () => TClient,
  options?: UseTriadChannelLifecycleOptions,
): UseTriadChannelResult<TClient> {
  const enabled = options?.enabled ?? true;
  const clientRef = useRef<TClient | null>(null);

  if (enabled && clientRef.current === null) {
    clientRef.current = factory();
  }

  useEffect(() => {
    if (!enabled) {
      const existing = clientRef.current;
      if (existing !== null) {
        clientRef.current = null;
        void existing.close();
      }
      return;
    }
    return () => {
      const existing = clientRef.current;
      if (existing !== null) {
        clientRef.current = null;
        void existing.close();
      }
    };
  }, [enabled]);

  const subscribe = (onStoreChange: () => void): (() => void) => {
    const current = clientRef.current;
    if (current === null) return () => {};
    return current.on('stateChange', () => onStoreChange());
  };

  const getSnapshot = (): ChannelState => {
    const current = clientRef.current;
    if (current === null) return 'closed';
    return current.state;
  };

  const state = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);

  // Non-null assertion: when \`enabled\` is true we created the client
  // above; when \`enabled\` is false we still need a value to return,
  // so we fall back to a disconnected stub. Callers of per-channel
  // hooks should gate their work on \`isOpen\` or \`state\`.
  const client = clientRef.current as TClient;
  return {
    client,
    state,
    isOpen: state === 'open',
  };
}
`;
}

// packages/channel-client/src/solid-template.ts
/**
 * Solid runtime template.
 *
 * Exports `renderSolidRuntime()` returning the TypeScript source
 * emitted alongside generated Solid channel hooks. The runtime owns
 * a tiny `createTriadChannelLifecycle` primitive that wraps a
 * vanilla `BaseChannelClient`-shaped object in Solid signals and
 * attaches a cleanup on unmount.
 *
 * The runtime has no compile-time dependency on any particular
 * channel: it is parametric over `TClient extends TriadChannelClientLike`.
 * Per-channel factories (emitted by `solid-hook-generator.ts`) wrap
 * it with typed message callbacks.
 */

export function renderSolidRuntime(): string {
  return `// Generated by @triadjs/channel-client — do not edit.
// Regenerate with: triad frontend generate --target channel-client-solid

import { createSignal, createEffect, onCleanup, type Accessor } from 'solid-js';
import type { ChannelState } from './client.js';

/**
 * Minimal structural shape every generated channel client satisfies.
 * The Solid lifecycle primitive works against this interface so it
 * does not need a per-channel import.
 */
export interface TriadChannelClientLike {
  readonly state: ChannelState;
  on(event: 'stateChange', cb: (state: ChannelState) => void): () => void;
  close(): Promise<void>;
}

export interface CreateTriadChannelResult<TClient extends TriadChannelClientLike> {
  /** Accessor returning the live client, or \`null\` while disabled. */
  client: Accessor<TClient | null>;
  /** Current connection state. Updates reactively on transition. */
  state: Accessor<ChannelState>;
  /** Convenience accessor equivalent to \`state() === 'open'\`. */
  isOpen: Accessor<boolean>;
}

export interface CreateTriadChannelLifecycleOptions {
  /**
   * When \`false\` (or returns \`false\`), no client is created and
   * the result reports \`'closed'\`. Flipping back to \`true\` creates
   * a fresh client. Defaults to \`true\`.
   */
  enabled?: Accessor<boolean> | boolean;
}

function resolveEnabled(value: Accessor<boolean> | boolean | undefined): boolean {
  if (value === undefined) return true;
  if (typeof value === 'boolean') return value;
  return value();
}

/**
 * Own a channel client across the lifetime of a Solid component.
 *
 * - The factory is invoked once per enabled reactivation.
 * - When \`enabled\` flips false, or the component unmounts, the
 *   previous client's \`close()\` is called.
 * - State updates flow through a signal, so Solid's reactivity picks
 *   up \`connecting → open\` transitions automatically.
 *
 * Changing connection options (url, params, headers) at runtime is
 * NOT supported: the factory runs once per enabled edge. To reconnect
 * against different options, re-mount the component.
 */
export function createTriadChannelLifecycle<TClient extends TriadChannelClientLike>(
  factory: () => TClient,
  options?: CreateTriadChannelLifecycleOptions,
): CreateTriadChannelResult<TClient> {
  const [client, setClient] = createSignal<TClient | null>(null);
  const [state, setState] = createSignal<ChannelState>('closed');

  createEffect(() => {
    const enabled = resolveEnabled(options?.enabled);
    if (!enabled) {
      const existing = client();
      setClient(null);
      setState('closed');
      if (existing !== null) void existing.close();
      return;
    }
    const instance = factory();
    setClient(() => instance);
    setState(instance.state);
    const unsubscribe = instance.on('stateChange', (next) => setState(next));
    onCleanup(() => {
      unsubscribe();
      setClient(null);
      setState('closed');
      void instance.close();
    });
  });

  const isOpen: Accessor<boolean> = () => state() === 'open';
  return { client, state, isOpen };
}
`;
}
